/**
*ORDEN 6
*@authors Mardiada y Sallopjo
*/
/*REGLAS y RELACION DE REGLAS*/
/**/
CREATE TABLE reglas
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,nombre VARCHAR (255) NOT NULL
	,descripcion VARCHAR (255) NULL
	,modificaM INTEGER NULL
	,modificaHA INTEGER NULL
	,modificaHP INTEGER NULL
	,modificaF INTEGER NULL
	,modificaR INTEGER NULL
	,modificaH INTEGER NULL
	,modificaI INTEGER NULL
	,modificaA INTEGER NULL
	,modificaL INTEGER NULL
	,estableceM INTEGER UNSIGNED NULL
	,estableceHA INTEGER UNSIGNED NULL
	,estableceHP INTEGER UNSIGNED NULL
	,estableceF INTEGER UNSIGNED NULL
	,estableceR INTEGER UNSIGNED NULL
	,estableceH INTEGER UNSIGNED NULL
	,estableceI INTEGER UNSIGNED NULL
	,estableceA INTEGER UNSIGNED NULL
	,estableceL INTEGER UNSIGNED NULL
	,efecto VARCHAR (20) NOT NULL
	,afectados VARCHAR (20) NOT NULL
	,activa BOOLEAN NOT NULL
	,PRIMARY KEY (id)
	,UNIQUE (nombre)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;

/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;


/**/
CREATE TABLE 
	(id INTEGER UNSIGNED AUTO_INCREMENT
	,
	,PRIMARY KEY (id)
	)engine=innoDB;